### ISSUE TITLE
How to install on Debian

### ISSUE THREAD

**Issue by adevoss** [Podcastindex-org/podping-hivewatcher#2]
After a fresh install of Debian 12 the following error appears after `poetry install`:
```
  PoetryException

  Failed to install /root/.cache/pypoetry/artifacts/1a/43/ed/2c19631c9ff378eba22e976d47dca45c4019aaab281a2ef35129184597/scrypt-0.8.20.tar.gz

  at /usr/lib/python3/dist-packages/poetry/utils/pip.py:58 in pip_install
       54│ 
       55│     try:
       56│         return environment.run_pip(*args)
       57│     except EnvCommandError as e:
    →  58│         raise PoetryException(f"Failed to install {path.as_posix()}") from e
       59│ 
```
How to install on Debian? Or is this a Debian bug?

Extra packages installed:
ii  python3-pip                     23.0.1+dfsg-1
ii  python3-pendulum                     2.1.2-4
ii  python3-poetry                       1.3.2+dfsg-3
ii  python3-poetry-core                  1.4.0-4

**Comment by agates** [comment]
Hi, is that the full error log?

Did you install from the git repo directly?

What version of python?

I highly recommend the docker/podman method if you can use that, but I can look into this some time soon with more information.

**Comment by adevoss** [comment]
Installed Debian 12 then
Python version: `3.11.2-1+b1`

Followed the readme:
Cloned the repo
`apt install python3-poetry`
cd to repo directory
poetry install (results in error)

When reviewing the error (above is not the full error) I saw a line:
`scrypt-1.2.1/libcperciva/crypto/crypto_aes.c:6:10: fatal error: openssl/aes.h: No such file or directory`
So I searched the packages of Debian and found the  `libssl-dev` contains that file.
`apt install libssl-dev` solved this error but not all errors.

hive-watcher.py is OK now, async-watcher.py is not.

When running `async-watcher.py`, first I got an error (missing module)
So I added `steem-async = "^2.1.0"` to `pyproject.toml` and the error was gone.
Then I got the same error with the pydantic module.
So I added `pydantic = "^2.1.1"` to `pyproject.toml` and the error was gone.

But when I run async-watcher.py I get Python errors from line 55.

Wrong version of `pydantic` maybe?

**Comment by adevoss** [comment]
```
Traceback (most recent call last):
  File "/root/hive-watcher/podping-hivewatcher/./async-watcher.py", line 55, in <module>
    class OpFiltered(BaseModel, Operation):
  File "/root/.cache/pypoetry/virtualenvs/hive-watcher-m-66ZQOO-py3.11/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 173, in __new__
    complete_model_class(
  File "/root/.cache/pypoetry/virtualenvs/hive-watcher-m-66ZQOO-py3.11/lib/python3.11/site-packages/pydantic/_internal/_model_construction.py", line 463, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/hive-watcher-m-66ZQOO-py3.11/lib/python3.11/site-packages/pydantic/main.py", line 549, in __get_pydantic_core_schema__
    return __handler(__source)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/hive-watcher-m-66ZQOO-py3.11/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/hive-watcher-m-66ZQOO-py3.11/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 426, in generate_schema
    return self._generate_schema_for_type(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/hive-watcher-m-66ZQOO-py3.11/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 458, in _generate_schema_for_type
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/hive-watcher-m-66ZQOO-py3.11/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 684, in _generate_schema
    return self._model_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/hive-watcher-m-66ZQOO-py3.11/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 528, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/hive-watcher-m-66ZQOO-py3.11/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 528, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/hive-watcher-m-66ZQOO-py3.11/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 848, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/hive-watcher-m-66ZQOO-py3.11/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 900, in _common_field_schema
    schema = self._apply_annotations(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/hive-watcher-m-66ZQOO-py3.11/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1586, in _apply_annotations
    schema = get_inner_schema(source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/hive-watcher-m-66ZQOO-py3.11/lib/python3.11/site-packages/pydantic/_internal/_schema_generation_shared.py", line 82, in __call__
    schema = self._handler(__source_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/hive-watcher-m-66ZQOO-py3.11/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 1550, in inner_handler
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/hive-watcher-m-66ZQOO-py3.11/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 689, in _generate_schema
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/hive-watcher-m-66ZQOO-py3.11/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 772, in match_type
    return self._match_generic_type(obj, origin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/hive-watcher-m-66ZQOO-py3.11/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 796, in _match_generic_type
    return self._union_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/hive-watcher-m-66ZQOO-py3.11/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 983, in _union_schema
    choices.append(self.generate_schema(arg))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/hive-watcher-m-66ZQOO-py3.11/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 426, in generate_schema
    return self._generate_schema_for_type(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/hive-watcher-m-66ZQOO-py3.11/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 458, in _generate_schema_for_type
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/hive-watcher-m-66ZQOO-py3.11/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 689, in _generate_schema
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/hive-watcher-m-66ZQOO-py3.11/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 776, in match_type
    return self._unknown_type_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/pypoetry/virtualenvs/hive-watcher-m-66ZQOO-py3.11/lib/python3.11/site-packages/pydantic/_internal/_generate_schema.py", line 375, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'privex.helpers.collections.DictObject'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.1.1/u/schema-for-unknown-type

```

**Comment by adevoss** [comment]
Tried to install it again last week and it works. Too many changes since so I can't give you a reason why it succeeded this time.
